"""p1_operational_reliability

Revision ID: 50b77a799c5c
Revises: b7e3d5a20c91
Create Date: 2026-09-08 23:51:29.468666
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50b77a799c5c'
down_revision: Union[str, None] = 'b7e3d5a20c91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# ---- 幂等护栏（自愈迁移）：对象已存在则跳过对应 DDL，详见 initial 迁移头部说明 ----
def _insp():
    return sa.inspect(op.get_bind())


def _has_table(name: str) -> bool:
    return _insp().has_table(name)


def _has_column(table: str, column: str) -> bool:
    insp = _insp()
    return insp.has_table(table) and any(c["name"] == column for c in insp.get_columns(table))


def _has_index(table: str, index: str) -> bool:
    # 索引或唯一约束（MySQL 唯一约束即唯一索引，两处都查）
    insp = _insp()
    if not insp.has_table(table):
        return False
    names = {i["name"] for i in insp.get_indexes(table)}
    names |= {u["name"] for u in insp.get_unique_constraints(table)}
    return index in names


def _has_fkey(table: str, name: str) -> bool:
    insp = _insp()
    return insp.has_table(table) and any(f.get("name") == name for f in insp.get_foreign_keys(table))


def _create_table_if_missing(name: str, *args, **kwargs):
    if not _has_table(name):
        op.create_table(name, *args, **kwargs)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _create_table_if_missing('ai_budgets',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('calls', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key', 'day')
    )
    _create_table_if_missing('ai_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=30), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if not _has_index('ai_usage', 'ix_ai_usage_project_id'):
        with op.batch_alter_table('ai_usage', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_ai_usage_project_id'), ['project_id'], unique=False)

    _create_table_if_missing('inspection_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('inspector_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['inspection_items.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if not _has_index('inspection_plans', 'ix_inspection_plans_project_id'):
        with op.batch_alter_table('inspection_plans', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_inspection_plans_project_id'), ['project_id'], unique=False)

    _create_table_if_missing('knowledge_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inspection_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'version', name='uq_knowledge_revision')
    )
    _create_table_if_missing('ai_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token', sa.String(length=40), nullable=True),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['inspection_records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_id')
    )
    if not _has_index('ai_jobs', 'ix_ai_jobs_status'):
        with op.batch_alter_table('ai_jobs', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_ai_jobs_status'), ['status'], unique=False)

    _create_table_if_missing('plan_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('inspector_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['inspection_plans.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['inspection_records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'scheduled_date', name='uq_plan_task_day'),
    sa.UniqueConstraint('record_id')
    )
    if not _has_index('plan_tasks', 'ix_plan_tasks_project_id'):
        with op.batch_alter_table('plan_tasks', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_plan_tasks_project_id'), ['project_id'], unique=False)

    _create_table_if_missing('deadline_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['rectify_orders.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if not _has_index('deadline_requests', 'ix_deadline_requests_order_id'):
        with op.batch_alter_table('deadline_requests', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_deadline_requests_order_id'), ['order_id'], unique=False)

    _create_table_if_missing('feedback_rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('submitter_id', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['rectify_orders.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'round', name='uq_feedback_round')
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        if not _has_column('attachments', 'upload_key'):
            batch_op.add_column(sa.Column('upload_key', sa.String(length=64), nullable=True))
        if not _has_column('attachments', 'evidence'):
            batch_op.add_column(sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
        if not _has_index('attachments', 'uq_attachment_upload'):
            batch_op.create_unique_constraint('uq_attachment_upload', ['project_id', 'uploader_id', 'upload_key'])

    with op.batch_alter_table('inspection_items', schema=None) as batch_op:
        if not _has_column('inspection_items', 'publication'):
            batch_op.add_column(sa.Column('publication', sa.String(length=20), server_default='legacy', nullable=False))
        if not _has_column('inspection_items', 'effective_from'):
            batch_op.add_column(sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True))
        if not _has_column('inspection_items', 'effective_until'):
            batch_op.add_column(sa.Column('effective_until', sa.DateTime(timezone=True), nullable=True))
        if not _has_column('inspection_items', 'approved_by'):
            batch_op.add_column(sa.Column('approved_by', sa.Integer(), nullable=True))
        if not _has_fkey('inspection_items', 'fk_item_approved_by'):
            batch_op.create_foreign_key('fk_item_approved_by', 'users', ['approved_by'], ['id'])

    with op.batch_alter_table('inspection_records', schema=None) as batch_op:
        if not _has_column('inspection_records', 'item_snapshot'):
            batch_op.add_column(sa.Column('item_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
        if not _has_column('inspection_records', 'location'):
            batch_op.add_column(sa.Column('location', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
        if not _has_column('inspection_records', 'request_key'):
            batch_op.add_column(sa.Column('request_key', sa.String(length=64), nullable=True))
        if not _has_column('inspection_records', 'request_hash'):
            batch_op.add_column(sa.Column('request_hash', sa.String(length=64), nullable=True))
        if not _has_column('inspection_records', 'confirm_key'):
            batch_op.add_column(sa.Column('confirm_key', sa.String(length=64), nullable=True))
        if not _has_column('inspection_records', 'confirm_hash'):
            batch_op.add_column(sa.Column('confirm_hash', sa.String(length=64), nullable=True))
        if not _has_index('inspection_records', 'uq_record_request'):
            batch_op.create_unique_constraint('uq_record_request', ['project_id', 'inspector_id', 'request_key'])

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        if not _has_column('notifications', 'lease_until'):
            batch_op.add_column(sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True))
        if not _has_column('notifications', 'claim_token'):
            batch_op.add_column(sa.Column('claim_token', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('claim_token')
        batch_op.drop_column('lease_until')

    with op.batch_alter_table('inspection_records', schema=None) as batch_op:
        batch_op.drop_constraint('uq_record_request', type_='unique')
        batch_op.drop_column('confirm_hash')
        batch_op.drop_column('confirm_key')
        batch_op.drop_column('request_hash')
        batch_op.drop_column('request_key')
        batch_op.drop_column('location')
        batch_op.drop_column('item_snapshot')

    with op.batch_alter_table('inspection_items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_item_approved_by', type_='foreignkey')
        batch_op.drop_column('approved_by')
        batch_op.drop_column('effective_until')
        batch_op.drop_column('effective_from')
        batch_op.drop_column('publication')

    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_constraint('uq_attachment_upload', type_='unique')
        batch_op.drop_column('evidence')
        batch_op.drop_column('upload_key')

    op.drop_table('feedback_rounds')
    with op.batch_alter_table('deadline_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deadline_requests_order_id'))

    op.drop_table('deadline_requests')
    with op.batch_alter_table('plan_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_tasks_project_id'))

    op.drop_table('plan_tasks')
    with op.batch_alter_table('ai_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_jobs_status'))

    op.drop_table('ai_jobs')
    op.drop_table('knowledge_revisions')
    with op.batch_alter_table('inspection_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspection_plans_project_id'))

    op.drop_table('inspection_plans')
    with op.batch_alter_table('ai_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_usage_project_id'))

    op.drop_table('ai_usage')
    op.drop_table('ai_budgets')
    # ### end Alembic commands ###
