"""initial 8 tables

Revision ID: 5ecb02e608dd
Revises: 
Create Date: 2026-09-05 16:59:03.454596
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ecb02e608dd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# ---- 幂等护栏（自愈迁移）----
# 背景：云托管容器可能在迁移执行中途被重启/掐断（重新部署、健康检查超时），而 MySQL
# DDL 即时提交、alembic 版本号在整个迁移跑完后才写入，会留下「部分表已建、版本号滞后」
# 的中间态；下次启动 alembic upgrade head 将以 1050 重复建表失败并永久无法部署。
# 护栏按实际库结构跳过已存在的表/列/索引/外键，使任意中间态都能收敛到最新版本。
def _insp():
    return sa.inspect(op.get_bind())


def _has_table(name: str) -> bool:
    return _insp().has_table(name)


def _create_table_if_missing(name: str, *args, **kwargs):
    if not _has_table(name):
        op.create_table(name, *args, **kwargs)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _create_table_if_missing('inspection_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('check_points', sa.Text(), nullable=False),
    sa.Column('basis', sa.String(length=500), nullable=False),
    sa.Column('defect_category', sa.String(length=20), nullable=False),
    sa.Column('risk_level', sa.String(length=10), nullable=False),
    sa.Column('applicable_types', sa.Text(), nullable=False),
    sa.Column('applicable_phases', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    _create_table_if_missing('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('project_type', sa.String(length=20), nullable=False),
    sa.Column('phase', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    _create_table_if_missing('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('specialty', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('wx_openid', sa.String(length=64), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    _create_table_if_missing('inspection_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('inspector_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('item_basis', sa.String(length=500), nullable=False),
    sa.Column('defect_category', sa.String(length=20), nullable=False),
    sa.Column('photo_path', sa.String(length=200), nullable=False),
    sa.Column('ai_result', sa.Text(), nullable=True),
    sa.Column('ai_mode', sa.String(length=10), nullable=True),
    sa.Column('human_verdict', sa.String(length=20), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['inspection_items.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    _create_table_if_missing('ai_feedbacks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('ai_defect', sa.Boolean(), nullable=False),
    sa.Column('human_defect', sa.Boolean(), nullable=False),
    sa.Column('consistent', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['inspection_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    _create_table_if_missing('rectify_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('order_no', sa.String(length=30), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('inspector_id', sa.Integer(), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=False),
    sa.Column('problem_location', sa.Text(), nullable=False),
    sa.Column('rectify_requirement', sa.Text(), nullable=False),
    sa.Column('basis', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('feedback_photo', sa.String(length=200), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('review_result', sa.String(length=20), nullable=True),
    sa.Column('review_comment', sa.String(length=500), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['inspection_records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_no')
    )
    _create_table_if_missing('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.String(length=500), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['rectify_orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    _create_table_if_missing('order_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=20), nullable=True),
    sa.Column('to_status', sa.String(length=20), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('remark', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['rectify_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_logs')
    op.drop_table('messages')
    op.drop_table('rectify_orders')
    op.drop_table('ai_feedbacks')
    op.drop_table('inspection_records')
    op.drop_table('users')
    op.drop_table('projects')
    op.drop_table('inspection_items')
    # ### end Alembic commands ###
