"""P03 multitenancy

Revision ID: b04b75072f3a
Revises: a23b57df5a34
Create Date: 2026-09-05 19:21:48.744033
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b04b75072f3a'
down_revision: Union[str, None] = 'a23b57df5a34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# ---- 幂等护栏（自愈迁移）：对象已存在则跳过对应 DDL，详见 initial 迁移头部说明 ----
def _insp():
    return sa.inspect(op.get_bind())


def _has_table(name: str) -> bool:
    return _insp().has_table(name)


def _has_column(table: str, column: str) -> bool:
    insp = _insp()
    return insp.has_table(table) and any(c["name"] == column for c in insp.get_columns(table))


def _has_index(table: str, index: str) -> bool:
    # 索引或唯一约束（MySQL 唯一约束即唯一索引，两处都查）
    insp = _insp()
    if not insp.has_table(table):
        return False
    names = {i["name"] for i in insp.get_indexes(table)}
    names |= {u["name"] for u in insp.get_unique_constraints(table)}
    return index in names


def _has_fkey(table: str, name: str) -> bool:
    insp = _insp()
    return insp.has_table(table) and any(f.get("name") == name for f in insp.get_foreign_keys(table))


def _create_table_if_missing(name: str, *args, **kwargs):
    if not _has_table(name):
        op.create_table(name, *args, **kwargs)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _create_table_if_missing('organizations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    _create_table_if_missing('project_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('specialty', sa.String(length=20), nullable=True),
    sa.Column('org_unit', sa.String(length=100), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', 'role', name='uq_member_project_user_role')
    )
    # SQLite batch 重建表要求约束具名，故所有外键显式命名。
    with op.batch_alter_table('ai_feedbacks', schema=None) as batch_op:
        if not _has_column('ai_feedbacks', 'org_id'):
            batch_op.add_column(sa.Column('org_id', sa.Integer(), nullable=True))
        if not _has_column('ai_feedbacks', 'project_id'):
            batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=True))
        if not _has_fkey('ai_feedbacks', 'fk_ai_feedbacks_project_id'):
            batch_op.create_foreign_key('fk_ai_feedbacks_project_id', 'projects', ['project_id'], ['id'])
        if not _has_fkey('ai_feedbacks', 'fk_ai_feedbacks_org_id'):
            batch_op.create_foreign_key('fk_ai_feedbacks_org_id', 'organizations', ['org_id'], ['id'])

    with op.batch_alter_table('inspection_items', schema=None) as batch_op:
        if not _has_column('inspection_items', 'org_id'):
            batch_op.add_column(sa.Column('org_id', sa.Integer(), nullable=True))
        if not _has_column('inspection_items', 'code'):
            batch_op.add_column(sa.Column('code', sa.String(length=50), nullable=True))
        if not _has_column('inspection_items', 'default_sla_hours'):
            batch_op.add_column(sa.Column('default_sla_hours', sa.Integer(), nullable=True))
        if not _has_column('inspection_items', 'version'):
            batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False))
        if not _has_column('inspection_items', 'updated_by'):
            batch_op.add_column(sa.Column('updated_by', sa.Integer(), nullable=True))
        if not _has_fkey('inspection_items', 'fk_items_updated_by'):
            batch_op.create_foreign_key('fk_items_updated_by', 'users', ['updated_by'], ['id'])
        if not _has_fkey('inspection_items', 'fk_items_org_id'):
            batch_op.create_foreign_key('fk_items_org_id', 'organizations', ['org_id'], ['id'])

    with op.batch_alter_table('inspection_records', schema=None) as batch_op:
        if not _has_column('inspection_records', 'org_id'):
            batch_op.add_column(sa.Column('org_id', sa.Integer(), nullable=False))
        if not _has_fkey('inspection_records', 'fk_records_org_id'):
            batch_op.create_foreign_key('fk_records_org_id', 'organizations', ['org_id'], ['id'])

    with op.batch_alter_table('messages', schema=None) as batch_op:
        if not _has_column('messages', 'org_id'):
            batch_op.add_column(sa.Column('org_id', sa.Integer(), nullable=True))
        if not _has_column('messages', 'project_id'):
            batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=True))
        if not _has_fkey('messages', 'fk_messages_project_id'):
            batch_op.create_foreign_key('fk_messages_project_id', 'projects', ['project_id'], ['id'])
        if not _has_fkey('messages', 'fk_messages_org_id'):
            batch_op.create_foreign_key('fk_messages_org_id', 'organizations', ['org_id'], ['id'])

    with op.batch_alter_table('projects', schema=None) as batch_op:
        if not _has_column('projects', 'org_id'):
            batch_op.add_column(sa.Column('org_id', sa.Integer(), nullable=False))
        if not _has_column('projects', 'code'):
            batch_op.add_column(sa.Column('code', sa.String(length=50), nullable=True))
        if not _has_column('projects', 'address'):
            batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=True))
        if not _has_column('projects', 'lng'):
            batch_op.add_column(sa.Column('lng', sa.Numeric(precision=10, scale=6), nullable=True))
        if not _has_column('projects', 'lat'):
            batch_op.add_column(sa.Column('lat', sa.Numeric(precision=10, scale=6), nullable=True))
        if not _has_column('projects', 'start_date'):
            batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=True))
        if not _has_column('projects', 'planned_end_date'):
            batch_op.add_column(sa.Column('planned_end_date', sa.Date(), nullable=True))
        if not _has_index('projects', 'uq_project_org_code'):
            batch_op.create_unique_constraint('uq_project_org_code', ['org_id', 'code'])
        if not _has_fkey('projects', 'fk_projects_org_id'):
            batch_op.create_foreign_key('fk_projects_org_id', 'organizations', ['org_id'], ['id'])

    with op.batch_alter_table('rectify_orders', schema=None) as batch_op:
        if not _has_column('rectify_orders', 'org_id'):
            batch_op.add_column(sa.Column('org_id', sa.Integer(), nullable=False))
        if not _has_column('rectify_orders', 'project_id'):
            batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=False))
        if not _has_fkey('rectify_orders', 'fk_orders_org_id'):
            batch_op.create_foreign_key('fk_orders_org_id', 'organizations', ['org_id'], ['id'])
        if not _has_fkey('rectify_orders', 'fk_orders_project_id'):
            batch_op.create_foreign_key('fk_orders_project_id', 'projects', ['project_id'], ['id'])

    # 删除 role/specialty/project_id（迁至 project_members）。SQLite batch 重建表时旧 project_id 外键随列删除自动消失。
    # MySQL 无表重建：project_id 外键（初始迁移未具名，MySQL 自动命名形如 users_ibfk_N）占用该列索引，
    # 直接 DROP COLUMN 报 1553，须先按库中实际外键名删除该列上的全部外键，再删列。
    if _has_column('users', 'project_id') and op.get_bind().dialect.name != 'sqlite':
        for _fk in _insp().get_foreign_keys('users'):
            if 'project_id' in (_fk.get('constrained_columns') or []) and _fk.get('name'):
                op.drop_constraint(_fk['name'], 'users', type_='foreignkey')

    with op.batch_alter_table('users', schema=None) as batch_op:
        if _has_column('users', 'role'):
            batch_op.drop_column('role')
        if _has_column('users', 'project_id'):
            batch_op.drop_column('project_id')
        if _has_column('users', 'specialty'):
            batch_op.drop_column('specialty')
        if not _has_fkey('users', 'fk_users_org_id'):
            batch_op.create_foreign_key('fk_users_org_id', 'organizations', ['org_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # batch 重建表时，删除相关列会一并移除其外键，无需显式 drop_constraint（兼容 SQLite）。
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_org_id', type_='foreignkey')
        batch_op.add_column(sa.Column('specialty', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('project_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=20), nullable=True))
        batch_op.create_foreign_key('fk_users_project_id', 'projects', ['project_id'], ['id'])

    with op.batch_alter_table('rectify_orders', schema=None) as batch_op:
        batch_op.drop_column('project_id')
        batch_op.drop_column('org_id')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint('uq_project_org_code', type_='unique')
        batch_op.drop_column('planned_end_date')
        batch_op.drop_column('start_date')
        batch_op.drop_column('lat')
        batch_op.drop_column('lng')
        batch_op.drop_column('address')
        batch_op.drop_column('code')
        batch_op.drop_column('org_id')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('project_id')
        batch_op.drop_column('org_id')

    with op.batch_alter_table('inspection_records', schema=None) as batch_op:
        batch_op.drop_column('org_id')

    with op.batch_alter_table('inspection_items', schema=None) as batch_op:
        batch_op.drop_column('updated_by')
        batch_op.drop_column('version')
        batch_op.drop_column('default_sla_hours')
        batch_op.drop_column('code')
        batch_op.drop_column('org_id')

    with op.batch_alter_table('ai_feedbacks', schema=None) as batch_op:
        batch_op.drop_column('project_id')
        batch_op.drop_column('org_id')

    op.drop_table('project_members')
    op.drop_table('organizations')
