"""P02 auth accounts security

Revision ID: a23b57df5a34
Revises: 5ecb02e608dd
Create Date: 2026-09-05 17:25:00.314295
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a23b57df5a34'
down_revision: Union[str, None] = '5ecb02e608dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# ---- 幂等护栏（自愈迁移）：对象已存在则跳过对应 DDL，详见 initial 迁移头部说明 ----
def _insp():
    return sa.inspect(op.get_bind())


def _has_table(name: str) -> bool:
    return _insp().has_table(name)


def _has_column(table: str, column: str) -> bool:
    insp = _insp()
    return insp.has_table(table) and any(c["name"] == column for c in insp.get_columns(table))


def _has_index(table: str, index: str) -> bool:
    # 索引或唯一约束（MySQL 唯一约束即唯一索引，两处都查）
    insp = _insp()
    if not insp.has_table(table):
        return False
    names = {i["name"] for i in insp.get_indexes(table)}
    names |= {u["name"] for u in insp.get_unique_constraints(table)}
    return index in names


def _create_table_if_missing(name: str, *args, **kwargs):
    if not _has_table(name):
        op.create_table(name, *args, **kwargs)


def _create_index_if_missing(table: str, index: str, columns, **kwargs):
    if _has_table(table) and not _has_index(table, index):
        op.create_index(index, table, columns, **kwargs)


def _add_column_if_missing(table: str, column: str, col):
    if not _has_column(table, column):
        op.add_column(table, col)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _create_table_if_missing('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.String(length=50), nullable=True),
    sa.Column('before', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('after', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    _create_table_if_missing('refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('replaced_by', sa.Integer(), nullable=True),
    sa.Column('ua', sa.String(length=300), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    _create_index_if_missing('refresh_tokens', 'ix_refresh_tokens_user_id', ['user_id'], unique=False)
    # NOT NULL 新列：先带 server_default 回填既有行，再去除 server_default 以与模型（Python 端默认）保持一致
    _add_column_if_missing('users', 'is_org_admin', sa.Column('is_org_admin', sa.Boolean(), nullable=False, server_default=sa.false()))
    _add_column_if_missing('users', 'org_id', sa.Column('org_id', sa.Integer(), nullable=True))
    _add_column_if_missing('users', 'status', sa.Column('status', sa.String(length=20), nullable=False, server_default='active'))
    _add_column_if_missing('users', 'wx_unionid', sa.Column('wx_unionid', sa.String(length=64), nullable=True))
    _add_column_if_missing('users', 'password_updated_at', sa.Column('password_updated_at', sa.DateTime(timezone=True), nullable=True))
    _add_column_if_missing('users', 'must_change_password', sa.Column('must_change_password', sa.Boolean(), nullable=False, server_default=sa.true()))
    _add_column_if_missing('users', 'failed_login_count', sa.Column('failed_login_count', sa.Integer(), nullable=False, server_default='0'))
    _add_column_if_missing('users', 'locked_until', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    _add_column_if_missing('users', 'token_version', sa.Column('token_version', sa.Integer(), nullable=False, server_default='0'))
    _add_column_if_missing('users', 'last_login_at', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    # 去除临时 server_default（最终 schema 由应用层负责默认值）。
    # 用 batch 模式以兼容 SQLite（SQLite 不支持 ALTER COLUMN DROP DEFAULT，batch 会重建表）。
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('is_org_admin', server_default=None)
        batch_op.alter_column('status', server_default=None)
        batch_op.alter_column('must_change_password', server_default=None)
        batch_op.alter_column('failed_login_count', server_default=None)
        batch_op.alter_column('token_version', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'token_version')
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_count')
    op.drop_column('users', 'must_change_password')
    op.drop_column('users', 'password_updated_at')
    op.drop_column('users', 'wx_unionid')
    op.drop_column('users', 'status')
    op.drop_column('users', 'org_id')
    op.drop_column('users', 'is_org_admin')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
